@startuml

!pragma teoz true
OpenWeatherMap <-- PollutionAPI: get air pollution
&OpenMeteo <-- WeatherAPI: get historical weather
OpenWeatherMap --> PollutionAPI: return pollution
&OpenMeteo --> WeatherAPI: return weather
WeatherAPI --> PositionOffsetter:(wind_speed, wind_dir)\n get new position
PositionOffsetter --> WeatherAPI: return new position 
WeatherAPI --> PollutionAPI: get pollution at new position
PollutionAPI --> OpenWeatherMap: get new pollution
OpenWeatherMap --> PollutionAPI:return new pollution
par
WeatherAPI --> LocalData: save weather
LocalData <-- PollutionAPI: save pollution
end
par
LocalData --> SKLearn: load weather
LocalData --> SKLearn: load pollution
end
SKLearn --> SKLearn: calling KNN 
@enduml
